app/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from dish import urls as dish_urls
from menu import urls as menu_urls
from cart import urls as cart_urls

urlpatterns = [
    path("admin/", include(wagtailadmin_urls)),
    path("dish/", include(dish_urls)),
    path("cart/", include(cart_urls), name='cart'),
    path("", include(menu_urls), name='menu'),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/<int:dish_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:dish_id>/<int:quantity>', views.cart_remove, name='cart_remove'),
]

dish/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("<slug:dish_slug>/", views.get_dish_info, name='dish'),
]

menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='menu'),
]

dish/models.py
from django.db import models

from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from wagtail.admin.panels import FieldPanel
from wagtail.models import Page
from wagtail.snippets.models import register_snippet

from transliterate import translit


class DishPage(Page):
    pass


@register_snippet
class Category(models.Model):
    name = models.CharField(max_length=255)

    def get_dish_list(self):
        return Dish.objects.filter(category=self)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


@register_snippet
class Dish(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='+', null=False, blank=False)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    panels = [
        FieldPanel('name'),
        FieldPanel('category'),
        FieldPanel('description'),
        FieldPanel('price'),
        FieldPanel('image'),
    ]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name[0].upper() + self.name[1:]
        self.description = self.description[0].upper() + self.description[1:]

        self.slug = slugify(translit(self.name, 'ru', reversed=True))
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('dish', kwargs={'dish_slug': self.slug})

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'

menu/models.py
from django import forms
from django.db import models

from wagtail.admin.panels import (FieldPanel,
                                  PageChooserPanel,
                                  InlinePanel,
                                  MultiFieldPanel,
                                  HelpPanel)
from wagtail.models import Page, Orderable
from wagtail.snippets.models import register_snippet

from modelcluster.models import ClusterableModel
from modelcluster.fields import ParentalKey


class MenuPage(Page):
    pass


class OrderPage(Page):
    pass


class LinkTextMixin(models.Model):
    title = models.CharField(max_length=20,
                             blank=False,
                             null=True)
    page = models.ForeignKey('wagtailcore.Page',
                             blank=True,
                             null=True,
                             on_delete=models.SET_NULL,
                             related_name='+')

    panels = [
        FieldPanel('title'),
        PageChooserPanel('page'),
    ]

    def __str__(self):
        return self.title


@register_snippet
class ItemOfHeader(LinkTextMixin, ClusterableModel):
    class TypeChoice(models.TextChoices):
        LINK = 'L', 'Link'
        DROPDOWN = 'D', 'Dropdown'

    type = models.TextField(max_length=1,
                            choices=TypeChoice.choices,
                            default=TypeChoice.LINK)

    panels = [
        LinkTextMixin.panels[0],
        FieldPanel('type', widget=forms.Select),
        LinkTextMixin.panels[1],
        MultiFieldPanel([
            InlinePanel('drop_down_item'),
        ], heading='Items'),
    ]

    class Meta:
        verbose_name = 'Элемент хеадера'
        verbose_name_plural = 'Элементы хеадера'


class ItemOfDropDown(LinkTextMixin, Orderable):
    parent_item = ParentalKey(
        ItemOfHeader,
        on_delete=models.CASCADE,
        related_name='drop_down_item',
    )

    panels = LinkTextMixin.panels

    def __str__(self):
        return LinkTextMixin.title

cart/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from dish.models import Dish


def cart_add(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    cart.add(dish)

    data = {
        'cart': cart.cart,
        'total_price': cart.get_total_price()
    }

    return JsonResponse(data)


def cart_remove(request, dish_id, quantity=0):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    cart.remove(dish, quantity)

    data = {
        'cart': cart.cart,
        'total_price': cart.get_total_price()
    }

    return JsonResponse(data)


def index(request):
    data = {'cart': Cart(request)}
    return render(request, 'cart/cart_page.html', data)

dish/views.py
from django.shortcuts import render, get_object_or_404
from .models import Dish
from cart.cart import Cart


def index(request):
    pass


def get_dish_info(request, dish_slug):
    dish = get_object_or_404(Dish, slug=dish_slug)
    cart = Cart(request)
    context = {
        'dish': dish,
        'cart': cart,
    }
    return render(request, 'dish/dish_page.html', context)

menu/views.py
from django.shortcuts import render
from dish.models import Category
from .models import ItemOfHeader
from cart.cart import Cart


def index(request):
    print(Cart(request).get_total_price())
    context = {
        'categories': Category.objects.all(),
        'header': ItemOfHeader.objects.all(),
        'cart': Cart(request),
    }
    return render(request, 'menu/menu_page.html', context)

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.models import Page

# To enable logging of search queries for use with the "Promoted search results" module
# <https://docs.wagtail.org/en/stable/reference/contrib/searchpromotions.html>
# uncomment the following line and the lines indicated in the search function
# (after adding wagtail.contrib.search_promotions to INSTALLED_APPS):

# from wagtail.contrib.search_promotions.models import Query


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)

        # To log this query for use with the "Promoted search results" module:

        # query = Query.get(search_query)
        # query.add_hit()

    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(
        request,
        "search/search.html",
        {
            "search_query": search_query,
            "search_results": search_results,
        },
    )

app/templates/base.html
{% load static %}
{% load wagtailcore_tags %}
{% load header_tags %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/css/menu_page.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    {% block static %} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% header_tag %}
<div class="container-lg content">
    {% block content %} {% endblock %}
</div>

<script type="text/javascript" src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
<script type="module" src="{% static '/js/index.js' %}"></script>

</body>
</html>

cart/templates/cart/cart_page.html
{% extends 'base.html' %}
{% load wagtailcore_tags %}

{% block content %}
    {% if not cart %}
        <p class="fs-2 text-center">Здесь будут отображаться блюда, добавленные в заказ</p>
    {% endif %}

    {% for item in cart %}
        {% with dish=item.dish %}
            <div id="order_item" class="">
                <div class="row align-items-center">
                    <div class="col-8">
                        <div class="row">
                            <p class="mx-2 my-0">
                                <a class="link-decoration-hover" href="{{ dish.get_absolute_url }}">
                                    {{ dish.name }}
                                </a>
                            </p>
                        </div>
                        <div class="row">
                            <p class="mx-2 my-0">
                                <a href="{% url 'cart:cart_remove' dish.id 1 %}" class="btn">
                                    <i class="bi bi-dash-lg"></i>
                                </a>
                                {{ item.quantity }}
                                <a href="{% url 'cart:cart_add' dish.id %}" class="btn">
                                    <i class="bi bi-plus-lg"></i>
                                </a>
                            </p>
                        </div>
                    </div>
                    <div class="col-2 ps-0">
                        <p class="mx-2 my-0 ms-0">
                            {% if item.quantity == 1 %}
                                {{ item.price }}₽
                            {% else %}
                                {{ item.price }}₽ x {{ item.quantity }}
                            {% endif %}
                        </p>
                    </div>
                    <div class="col-2 text-end p-0 pe-2">
                        <a class="btn" href="{% url 'cart:cart_remove' dish.id 0 %}">
                            <i class="bi bi-x-lg"></i>
                        </a>
                    </div>
                </div>
            </div>
        {% endwith %}
    {% endfor %}
    <hr>
    <div class="row align-items-center bold">
        <div id="totalPrice" class="col-8">
            <p class="fs-4 ms-2">Итого:</p>
        </div>
        <div class="col-4 p-0 pe-2 text-start">
            <p class="fs-4">{{ cart.get_total_price }}₽</p>
        </div>
    </div>

    <button class="btn btn-buy text-center px-4 py-2 mt-3 fs-5">
        Перейти к оплате
    </button>

{% endblock %}

dish/templates/dish/dish_page.html
{% extends 'base.html' %}
{% load static wagtailimages_tags cart_tags %}

{% block static %}
    <link rel="stylesheet" href="{% static '/css/dish_page.css' %}">
{% endblock %}

{% block content %}
    <button onclick="
            if (window.history.length > 1)
            window.history.back();
            else
            document.location.href='{% url 'menu' %}';
            " id="backToMenu"
            class="bold btn d-flex align-items-center text-decoration-none gap-3">
        <i class="bi bi-arrow-return-left"></i>
    </button>
    <div class="wrapper row">
        <div class="col-lg-12 col-xl-6">
            {% image dish.image original as image %}
            <div class="square-image mb-md-5">
                {% if image %}
                    <img src="{{ image.url }}" alt="{{ dish.name }}">
                {% else %}
                    <p class="text-center bold position-relative top-50 translate-middle-y m-0">
                        Изображение отсутствует
                    </p>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-12 col-xl-6">
            <p class="bold fs-1">
                {{ dish.name }}
            </p>
            <p class="fs-4 me-md-4">
                {{ dish.description }}
            </p>
            <p class="bold fs-2">
                {{ dish.price }} ₽
            </p>

            {% get_quantity dish.id as quantity %}
            {% if quantity.quantity > 0 %}
                <p class="bold">
                    <a href="{% url 'cart:cart_remove' dish.id 1 %}" class="btn">
                        <i class="bi bi-dash-lg"></i>
                    </a>
                    {{ quantity.quantity }}
                    <a href="{% url 'cart:cart_add' dish.id %}" class="btn">
                        <i class="bi bi-plus-lg"></i>
                    </a>
                </p>
            {% else %}
                <a href="{% url 'cart:cart_add' dish.id %}"
                   class="btn btn-buy">Добавить</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

menu/templates/menu/menu_page.html
{% extends 'base.html' %}
{% load wagtailimages_tags wagtailcore_tags cart_tags %}

{% block content %}
    <div class="row">
        {% for category in categories %}
            <p class="d-flex flex-row-reverse justify-content-end">
                <a class="pseudo-anchor bold fs-3 hover-decoration"
                   href="#{{ category }}">
                    {{ category }}
                </a>
                <i class="anchor-hash fs-3 bi bi-hash"></i>
                <a id="{{ category }}" class="anchor"></a>
            </p>

            {% for dish in category.get_dish_list %}
                <div class="col-xl-4 col-md-6 d-flex justify-content-center">
                    <div class="card my-3" style="width: 18rem;">
                        <div class="h-80 position-absolute w-100"
                             onclick="document.location.href='{{ dish.get_absolute_url }}'"></div>
                        <div class="card-img-top">
                            {% image dish.image original as image %}
                            {% if image %}
                                <img src="{{ image.url }}" alt="{{ dish.name }}">
                            {% else %}
                                <p class="text-center bold position-relative top-50 translate-middle-y m-0">
                                    Изображение отсутствует
                                </p>
                            {% endif %}
                        </div>
                        <form class="card-body">
                            <h5 class="card-title fs-4">{{ dish.price }} ₽</h5>
                            <b class="card-subtitle">{{ dish.name }}</b>
                            <p class="card-text">{{ dish.description }}</p>
                            <div class="in-cart-button" id="dish_{{ dish.id }}">
                                {% get_quantity dish.id as quantity %}

                                {% if quantity.quantity > 0 %}
                                    <p class="bold" id="edit_cart">
                                        {% else %}
                                    <p class="bold d-none" id="edit_cart">
                                {% endif %}

                                    <a href="{% url 'cart:index' %}" class="btn btn-buy">
                                        К заказу
                                    </a>
                                    <a
                                       class="btn" onclick="ajax_query({{ dish.id}}, 1)">
                                        <i class="bi bi-dash-lg"></i>
                                    </a>
                                    <a class="text-decoration-none" id="quantity">
                                        {{ quantity.quantity }}
                                    </a>
                                    <a
                                       class="btn" onclick="ajax_query({{ dish.id }})">
                                        <i class="bi bi-plus-lg"></i>
                                    </a>
                                </p>

                                {% if quantity.quantity == 0 %}
                                    <a class="w-100 btn btn-buy" id="in_cart"
                                       onclick="ajax_query( {{ dish.id }} )">
                                        Добавить
                                    </a>
                                {% else %}
                                    <a class="w-100 btn btn-buy d-none" id="in_cart"
                                       onclick="ajax_query( {{ dish.id }} )">
                                        Добавить
                                    </a>
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
    </div>


{% endblock %}

menu/templates/tags/header.html
{% load wagtailcore_tags %}

<nav class="navbar navbar-expand-lg fade-navbar fixed-top">
    <div class="container-lg flex-row-reverse">
        <button class="btn text-end nav-link text-white" onclick="document.location.href='{% url 'cart:index' %}'">
            <a class="bold d-flex flex-direction-row gap-2 text-white basket-button text-decoration-none">
                <p class="m-0">Заказ</p>
                <div class="bi bi-bag"></div>
            </a>
            <p class="fs-6 thin m-0 p-0" id="total-price">({{ cart.get_total_price }}₽)</p>
        </button>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Переключатель навигации">
            <i class="bi bi-list"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <div class="dropdown">
                    <a class='text-decoration-none'>
                        <p class="bold nav-link me-2 mb-0 text">
                            Меню
                            <i class="bi bi-caret-down dropdown-down"></i>
                        </p>
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li>
                                <a class="dropdown-item" href="{% url 'menu' %}#{{ category }}">
                                    {{ category.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                {% for item in header %}
                    {% if item.type == 'L' %}
                        <li><a href="{% pageurl item.page %}" class="bold nav-link me-2 text">{{ item.title }}</a>
                        </li>
                    {% elif item.type == 'D' %}
                        <div class="dropdown">
                            <a class='text-decoration-none'>
                                <p class="bold nav-link me-2 mb-0 text">
                                    {{ item.title }}
                                    <i class="bi bi-caret-down dropdown-down"></i>
                                </p>
                            </a>
                            <ul class="dropdown-menu">
                                {% for item in item.drop_down_item.all %}
                                    <li><a class="dropdown-item" href="{% pageurl item.page %}">{{ item.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>

search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
<h1>Search</h1>

<form action="{% url 'search' %}" method="get">
    <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
    <input type="submit" value="Search" class="button">
</form>

{% if search_results %}
<ul>
    {% for result in search_results %}
    <li>
        <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
        {% if result.search_description %}
        {{ result.search_description }}
        {% endif %}
    </li>
    {% endfor %}
</ul>

{% if search_results.has_previous %}
<a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
{% endif %}

{% if search_results.has_next %}
<a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
{% endif %}
{% elif search_query %}
No results found
{% endif %}
{% endblock %}